version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - 'database-volume:/data'
        ports:
            - '27017:27017'
        restart: always

volumes:
  database-volume:
